updat yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -27,6 +27,11 @@ jobs:
           script: |
             cd docare/main/DocareWeb
             git pull
+            if ! command -v npm &> /dev/null; then
+              echo "npm could not be found. Installing Node.js and npm..."
+              curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -
+              sudo apt-get install -y nodejs
+            fi
             npm install
             npm run build
             cp -rf ./build/* ~/public_html/docaremain
